#pragma once
#ifndef __PLAYER_ANIMATION_STATE__
#define __PLAYER_ANIMATION_STATE__

enum class PlayerAnimationState
{
	PLAYER_IDLE_RIGHT,
	PLAYER_IDLE_LEFT,
	PLAYER_RUN_RIGHT,
	PLAYER_RUN_LEFT,
	PLAYER_ATTACK_CLOSE,
	PLAYER_ATTACK_FIRE,
	NUM_OF_ANIMATION_STATES
};
enum class EnemyAnimatioState
{
	ENEMY_IDLE_RIGHT,
	ENEMY_IDLE_LEFT,
	ENEMY_RUN_RIGHT,
	ENEMY_RUN_LEFT,
	ENEMY_HIT,
	ENEMY_DIE,
	NUM_OF_ANIMATION_STATES
};

enum class HPAnimationState
{
	FULL_HP,
	THREE_QUARTERS_HP,
	HALF_HP,
	QUARTER_HP,
	NO_HP
};
#endif /* defined (__PLAYER_ANIMATION_STATE__)*/